**Multivariate Linear Regression**

In [2]:
import numpy as np


In [3]:
## dataset generator

def genData(nPoints, d):
    
    ## nPoints = number of points
    ## d = number of dimensions
    
    betas = np.random.uniform(-10,10, d+1)
    sigmaSquared = np.random.uniform(0, 10)

    X = []
    y = []
    for i in range(nPoints):
        x = np.random.uniform(-100,100,d+1)
        x[0]=1
        X.append(x)
        val = np.dot(betas,np.array(x))  + np.random.normal(0,sigmaSquared)
        y.append(val)
    X = np.array(X)
    y = np.array(y)
    print(betas)
    return X,y


** Linear Regression: Version 1 **
Use the closed-form solution for multivariate linear regression to find the coefficients


In [4]:
nPts = 200
dim = 4

X,y =  genData(nPts, dim)

[ 2.44090082 -2.14039559 -9.52417063 -5.92120863  2.48930533]


In [5]:
### Let's find the coefficients using the closed solution formula
##  beta = (X^T X)^-1 X^T y

### betaHat = 

In [6]:
betaHat


array([ 3.3483254 , -2.1431617 , -9.53466265, -5.90281339,  2.49442874])

** Linear Regression: Version 2** 

Use NumPy system of linear equations solver

In [60]:
### Matrix

## Mx = 

## Vector

# v = 

## use the solver

# betaHat1 = 


In [61]:
betaHat1

array([ 0.10701503, -3.06611462, -0.3891284 ,  0.59977734,  2.35812711])

** Linear Regression: Version 3 **

Iterative 